;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Fri Apr 1 2022
; Processor: AT89C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Setup

;====================================================================
; CODE SEGMENT
;====================================================================

      org   0100h
Setup:	
      MOV R0, #017h
      MOV R1, #03BH
      MOV R2, #000H
      MOV R3, #000H
      JMP Loop
      ;R0 = HOUR
      ;R1 = MINUTE
      ;R2 = SEC
      ;R3 = COUNT FROM 0 - 250 -> TIMER(4ms)*250 = 1s
      ; Write your code here
Loop:	

; xem vòng 1 loop bao nhiêu th?i gian, d?m s? loop d? d? 1s, 1 
      DEC R3
      ACALL Scan
      ACALL check0
      JMP Loop


;R3, R2, R1, R0
Scan:
      MOV A, R0
      MOV B, #0AH
      DIV AB
      CLR P3.7
      MOV P3, A
      SETB P3.4
      ACALL Delay
      
      CLR P3.4
      MOV P3, B
      SETB P3.5
      ACALL Delay
      
      MOV A, R1
      MOV B, #0AH
      DIV AB
      CLR P3.5
      MOV P3, A
      SETB P3.6
      ACALL Delay
      
      CLR P3.6
      MOV P3, B
      SETB P3.7
      ACALL Delay
      RET


      
checkHour:
      CJNE R0, #018h, returnCheckHour
      MOV R0, #0
returnCheckHour:
      RET

checkMin:
      CJNE R1, #03CH, returnCheckSec
      MOV R1, #0
      INC R0
      ACALL checkHour
returnCheckMin:
      RET

checkSec:
      CJNE R2, #03BH, returnCheckSec
      MOV R2, #0
      INC R1
      ACALL checkMin
returnCheckSec:
      RET

check0:
      CJNE R3, #000H, returnCheck0
      MOV R3, #0FAH
      INC R2
      ACALL checkSec
returnCheck0:
      RET



      
Delay: 
      MOV R6, #250D
      MOV R7, #250D
Label1: DJNZ R6, Label1
Label2: DJNZ R7, Label2
      RET
;====================================================================
      END
; b? tr? vài giây dù m?i b?t d?u d?m
