;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Fri Mar 18 2022
; Processor: AT89C51
; Compiler:  ASEM-51 (Proteus)
;====================================================================

$NOMOD51
$INCLUDE (8051.MCU)

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      org   0000h
      jmp   Start
      
;====================================================================
; CODE SEGMENT
;====================================================================
      org   0100h
      
Start:	
      MOV P0, #0FFh
      MOV P1, #0FFh
      MOV P2, #0FFH
      MOV P3, #0FFH
      JMP Loop
       ; Write your code here
 
 Effect1_a: 
  
      CLR P0.0
      ACALL Delay
      CLR P0.1
      ACALL Delay
      CLR P0.2
      ACALL Delay
      CLR P0.3
      ACALL Delay
      CLR P0.4
      ACALL Delay
      CLR P0.5
      ACALL Delay
      CLR P0.6
      ACALL Delay
      CLR P0.7
      ACALL Delay
      
      CLR P1.0
      ACALL Delay
      CLR P1.1
      ACALL Delay
      CLR P1.2
      ACALL Delay
      CLR P1.3
      ACALL Delay
      CLR P1.4
      ACALL Delay
      CLR P1.5
      ACALL Delay
      CLR P1.6
      ACALL Delay
      CLR P1.7
      ACALL Delay
      
      CLR P2.0
      ACALL Delay
      CLR P2.1
      ACALL Delay
      CLR P2.2
      ACALL Delay
      CLR P2.3
      ACALL Delay
      CLR P2.4
      ACALL Delay
      CLR P2.5
      ACALL Delay
      CLR P2.6
      ACALL Delay
      CLR P2.7
      ACALL Delay
      
      CLR P3.0
      ACALL Delay
      CLR P3.1
      ACALL Delay
      CLR P3.2
      ACALL Delay
      CLR P3.3
      ACALL Delay
      CLR P3.4
      ACALL Delay
      CLR P3.5
      ACALL Delay
      CLR P3.6
      ACALL Delay
      CLR P3.7
      ACALL Delay
      
      RET
      
Effect1_b:
      SETB P0.0
      ACALL Delay
      SETB P0.1
      ACALL Delay
      SETB P0.2
      ACALL Delay
      SETB P0.3
      ACALL Delay
      SETB P0.4
      ACALL Delay
      SETB P0.5
      ACALL Delay
      SETB P0.6
      ACALL Delay
      SETB P0.7
      ACALL Delay
      
      SETB P1.0
      ACALL Delay
      SETB P1.1
      ACALL Delay
      SETB P1.2
      ACALL Delay
      SETB P1.3
      ACALL Delay
      SETB P1.4
      ACALL Delay
      SETB P1.5
      ACALL Delay
      SETB P1.6
      ACALL Delay
      SETB P1.7
      ACALL Delay
      
      SETB P2.0
      ACALL Delay
      SETB P2.1
      ACALL Delay
      SETB P2.2
      ACALL Delay
      SETB P2.3
      ACALL Delay
      SETB P2.4
      ACALL Delay
      SETB P2.5
      ACALL Delay
      SETB P2.6
      ACALL Delay
      SETB P2.7
      ACALL Delay
      
      SETB P3.0
      ACALL Delay
      SETB P3.1
      ACALL Delay
      SETB P3.2
      ACALL Delay
      SETB P3.3
      ACALL Delay
      SETB P3.4
      ACALL Delay
      SETB P3.5
      ACALL Delay
      SETB P3.6
      ACALL Delay
      SETB P3.7
      ACALL Delay

      RET
 Effect2:
      
      CLR P0.0
      CLR P0.2
      CLR P0.4
      CLR P0.6
      CLR P1.0
      CLR P1.2
      CLR P1.4
      CLR P1.6
      CLR P2.0
      CLR P2.2
      CLR P2.4
      CLR P2.6
      CLR P3.0
      CLR P3.2
      CLR P3.4
      CLR P3.6
      SETB P0.1
      SETB P0.3
      SETB P0.5
      SETB P0.7
      SETB P1.1
      SETB P1.3
      SETB P1.5
      SETB P1.7
      SETB P2.1
      SETB P2.3
      SETB P2.5
      SETB P2.7
      SETB P3.1
      SETB P3.3
      SETB P3.5
      SETB P3.7
      ACALL Delay
      ACALL Delay
      ACALL Delay
      ACALL Delay
      
      CLR P0.1
      CLR P0.3
      CLR P0.5
      CLR P0.7
      CLR P1.1
      CLR P1.3
      CLR P1.5
      CLR P1.7
      CLR P2.1
      CLR P2.3
      CLR P2.5
      CLR P2.7
      CLR P3.1
      CLR P3.3
      CLR P3.5
      CLR P3.7
      SETB P0.0
      SETB P0.2
      SETB P0.4
      SETB P0.6
      SETB P1.0
      SETB P1.2
      SETB P1.4
      SETB P1.6
      SETB P2.0
      SETB P2.2
      SETB P2.4
      SETB P2.6
      SETB P3.0
      SETB P3.2
      SETB P3.4
      SETB P3.6
      ACALL Delay
      ACALL Delay
      ACALL Delay
      ACALL Delay
      RET
Effect3:
      
      MOV P0, #0h
      MOV P1, #0h
      MOV P2, #0H
      MOV P3, #0H
      
      MOV A, #00000001B
 Port0:
      MOV P0, A
      ACALL Delay
      RL A
      CJNE A, #00000001B, Port0
      MOV P0, #00000000B
      
      MOV A, #00000001B
   Port1:
      MOV P1, A
      ACALL Delay
      RL A
      CJNE A, #00000001B, Port1
      MOV P1, #00000000B
      
      MOV A, #00000001B
  Port2:
      MOV P2, A
      ACALL Delay
      RL A
      CJNE A,#00000001B, Port2
      MOV P2, #00000000B
      
      MOV A, #00000001B
  Port3:
      MOV P3, A
      ACALL Delay
      RL A
      CJNE A, #00000001B, Port3
      MOV P3, #00000000B
      
      RET
      
Delay: ;50ms
      MOV TMOD, #001H 
      MOV TH0, #03CH
      MOV TL0, #0B0H 
      SETB TR0 
Here: JNB TF0, Here
      CLR TR0
      CLR TF0
      RET
     
Loop: 

      ACALL Effect1_a
      ACALL Effect1_b
      ACALL Effect1_a
      
      MOV R0, #0
LoopE2:
      ACALL Effect2
      INC R0
      CJNE R0, #10, LoopE2
      
      ACALL Effect3
      ACALL Effect3
      ACALL Effect3
      
      MOV P0, #0FFh
      MOV P1, #0FFh
      MOV P2, #0FFH
      MOV P3, #0FFH
      JMP Loop



     
;====================================================================
endd:
      END
